FROM node:17-alpine3.12

RUN mkdir /home/angular/
WORKDIR /home/angular/

COPY package.json /home/angular/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9
RUN npm install --save @angular/material @angular/cdk @angular/animations

COPY ./ /home/angular/

CMD [""]

# EXPOSE 4200

# ENTRYPOINT ["ng", "serve", "--host", "0.0.0.0", "--poll", "500"]
