version: "3.9"
services:

  frontend:
    image: investing_app_frontend:0.0.1 
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: investing_app
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - database

  database:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      
volumes:
  redis:
  
networks:
  default:
    external:
      name: investoverlaynetwork