version: "3.9"
services:

  frontend:
    image: investing_app_frontend:0.0.1 
    ports:
      - "80:80"
    networks:
      - investing-app-network
    depends_on:
      - backend

  backend:
    image: investing_app_backend:0.0.1
    ports:
      - "8080:8080"
    networks:
      - investing-app-network
  
networks:
  investing-app-network:
    attachable: true