version: "3.9"
services:

  frontend:
    build: 
      context:      .\frontend
      dockerfile:   .\Dockerfile-Prod
    ports:
      - "80:80"
    networks:
      - investing-app-network
    depends_on:
      - backend

  backend:
    build: 
      context:      .\backend
      dockerfile:   .\Dockerfile-Prod
    ports:
      - "8080:8080"
    networks:
      - investing-app-network
  
networks:
  investing-app-network:
    attachable: true