version: "3.9"
services:

  frontend:
    build: .\frontend
    ports:
      - "80:80"
    networks:
      - investing-app-network
    depends_on:
      - backend

  backend:
    build: .\backend
    ports:
      - "8080:8080"
    networks:
      - investing-app-network
  
networks:
  investing-app-network:
    attachable: true