version: "3.9"
services:

  frontend:
    container_name: frontend-prod
    image:          investing-app-frontend-prod
    build: 
      context:      .\frontend
      dockerfile:   .\Dockerfile-Prod
    ports:
      - "4200:80"
    networks:
      - investing-app-network
    depends_on:
      - backend

  backend:
    container_name: backend-prod
    image:          investing-app-backend-prod
    build: 
      context:      .\backend
      dockerfile:   .\Dockerfile-Prod
    ports:
      - "8080:8080"
    networks:
      - investing-app-network
  
networks:
  investing-app-network:
    attachable: true