FROM maven:3.8-openjdk-11-slim

RUN mkdir /home/springboot/
WORKDIR /home/springboot/

# download all the dependency in the pom file
COPY ./pom.xml /home/springboot/pom.xml 
RUN mvn dependency:resolve


# copy the project
COPY ./ /home/springboot/

ENTRYPOINT ["tail", "-f", "/dev/null"]

# CMD [""]

# build the project
# RUN mvn clean install

# WORKDIR /home/springboot/

# EXPOSE 8080

# ENTRYPOINT ["java", "-jar", "/home/springboot/target/InvestingApp-0.0.2.jar"]


# For vs code:

# download vs-code and extensions
# WORKDIR /home/
# RUN apt-get -y update
# RUN curl -O https://az764295.vo.msecnd.net/stable/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/code_1.62.3-1637137107_amd64.deb
# RUN apt-get -y install ./code_1.62.3-1637137107_amd64.deb
# vscjava.vscode-java-debug
# vscjava.vscode-java-pack
# redhat.java
# vscjava.vscode-maven
# vscjava.vscode-java-dependency
# vscjava.vscode-java-test
# visualstudioexptteam.vscodeintellicode


## For IntelliJ IDEA you need:

## to update download an ssh server
# RUN apt-get -y update
# RUN apt-get -y install openssh-server

## to edit the ssh configuration
# RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
# RUN echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config

## to download the INtelliJ backend (optional)
# RUN curl -fSsL --output '/root/.cache/JetBrains/RemoteDev/dist/2d901dd26b850_ideaIU-2021.3.tar.gz' 'https://download.jetbrains.com/idea/ideaIU-2021.3.tar.gz'

## to turn on the ssh server on startup
# ENTRYPOINT ["service", "ssh", "start", "-D"]